def createPoison(pocet: number):
    global piece_of_poison
    for index in range(pocet):
        piece_of_poison = sprites.create(img("""
                ........................
                            ........................
                            ........................
                            ........................
                            ..........ffff..........
                            ........ff1111ff........
                            .......fb111111bf.......
                            .......f11111111f.......
                            ......fd11111111df......
                            ......fd11111111df......
                            ......fddd1111dddf......
                            ......fbdbfddfbdbf......
                            ......fcdcf11fcdcf......
                            .......fb111111bf.......
                            ......fffcdb1bdffff.....
                            ....fc111cbfbfc111cf....
                            ....f1b1b1ffff1b1b1f....
                            ....fbfbffffffbfbfbf....
                            .........ffffff.........
                            ...........fff..........
                            ........................
                            ........................
                            ........................
                            ........................
            """),
            SpriteKind.enemy)
        piece_of_poison.set_position(randint(28, 228), randint(28, 228))
def createFood(pocet2: number):
    global piece_of_food
    for index2 in range(pocet2):
        piece_of_food = sprites.create(img("""
                . . 2 2 b b b b b . . . . . . . 
                            . 2 b 4 4 4 4 4 4 b . . . . . . 
                            2 2 4 4 4 4 d d 4 4 b . . . . . 
                            2 b 4 4 4 4 4 4 d 4 b . . . . . 
                            2 b 4 4 4 4 4 4 4 d 4 b . . . . 
                            2 b 4 4 4 4 4 4 4 4 4 b . . . . 
                            2 b 4 4 4 4 4 4 4 4 4 e . . . . 
                            2 2 b 4 4 4 4 4 4 4 b e . . . . 
                            . 2 b b b 4 4 4 b b b e . . . . 
                            . . e b b b b b b b e e . . . . 
                            . . . e e b 4 4 b e e e b . . . 
                            . . . . . e e e e e e b d b b . 
                            . . . . . . . . . . . b 1 1 1 b 
                            . . . . . . . . . . . c 1 d d b 
                            . . . . . . . . . . . c 1 b c . 
                            . . . . . . . . . . . . c c . .
            """),
            SpriteKind.food)
        piece_of_food.set_position(randint(28, 228), randint(28, 228))
piece_of_food: Sprite = None
piece_of_poison: Sprite = None
tiles.set_current_tilemap(tilemap("""
    level1
"""))
eater = sprites.create(img("""
        ........................
            ........................
            ........................
            ...........ccc..........
            ...........cccc.........
            .......ccc..ccccccc.....
            .......cccccc555555cc...
            ........ccb5555555555c..
            .....cc..b555555555555c.
            .....cccb55555bcc555555c
            ......cb555555555c55d55c
            ......b5555555555555555c
            ...cc.b555dd5555bb1bbbc.
            ....ccd55ddddd5bbbb335c.
            ...ccbdddddddd5bbbb335c.
            .ccccddddddddd55bbb335c.
            cdcccdddddb55bb5bb3335c.
            cddbddddddb555bb5b3335c.
            cddddddddddb5555b53335c.
            ccddddddbd55bb55c5555c..
            .ccddddbbbdd55cccbccc...
            ...ccbbbcbddddccdddc....
            .....ccccdd555dccccc....
            ........cccccccc........
    """),
    SpriteKind.player)
eater.set_position(25, 25)
controller.move_sprite(eater, 100, 100)
scene.camera_follow_sprite(eater)
createFood(10)
createPoison(5)

def on_update_interval():
    pass
game.on_update_interval(1000, on_update_interval)
