function createPoison (pocet: number) {
    for (let index = 0; index < pocet; index++) {
        piece_of_poison = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        piece_of_poison.setPosition(randint(28, 228), randint(28, 228))
    }
}
function createFood (pocet: number) {
    for (let index = 0; index < pocet; index++) {
        piece_of_food = sprites.create(img`
            . . 2 2 b b b b b . . . . . . . 
            . 2 b 4 4 4 4 4 4 b . . . . . . 
            2 2 4 4 4 4 d d 4 4 b . . . . . 
            2 b 4 4 4 4 4 4 d 4 b . . . . . 
            2 b 4 4 4 4 4 4 4 d 4 b . . . . 
            2 b 4 4 4 4 4 4 4 4 4 b . . . . 
            2 b 4 4 4 4 4 4 4 4 4 e . . . . 
            2 2 b 4 4 4 4 4 4 4 b e . . . . 
            . 2 b b b 4 4 4 b b b e . . . . 
            . . e b b b b b b b e e . . . . 
            . . . e e b 4 4 b e e e b . . . 
            . . . . . e e e e e e b d b b . 
            . . . . . . . . . . . b 1 1 1 b 
            . . . . . . . . . . . c 1 d d b 
            . . . . . . . . . . . c 1 b c . 
            . . . . . . . . . . . . c c . . 
            `, SpriteKind.Food)
        piece_of_food.setPosition(randint(28, 228), randint(28, 228))
    }
}
let piece_of_food: Sprite = null
let piece_of_poison: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
let eater = sprites.create(assets.image`Eater`, SpriteKind.Player)
eater.setPosition(25, 25)
controller.moveSprite(eater, 100, 100)
scene.cameraFollowSprite(eater)
createFood(10)
createPoison(5)
game.onUpdateInterval(1000, function () {
	
})
